
### REST Client (VSCode REST Client extension)
# Remplacez ./debug/test-image.png par le chemin de votre image locale
POST http://localhost:5000/api/upload
Content-Type: multipart/form-data; boundary=----WebKitFormBoundary7MA4YWxkTrZu0gW

------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="file"; filename="test-image.png"
Content-Type: image/png

< ./img/maquette.png
------WebKitFormBoundary7MA4YWxkTrZu0gW--


### REST Client (VSCode REST Client extension)
# Remplacez ./debug/test-image.png par le chemin de votre image locale
POST http://localhost:5000/api/upload
Content-Type: multipart/form-data; boundary=----WebKitFormBoundary7MA4YWxkTrZu0gW

------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="file"; filename="test-image.jpg"
Content-Type: image/jpeg

< ./img/advice.jpg
------WebKitFormBoundary7MA4YWxkTrZu0gW--



### REST Client (VSCode REST Client extension)
# Remplacez ./debug/test-image.png par le chemin de votre image locale
POST https://pic-to-tailwind-b3ph.vercel.app/upload/api/upload
Content-Type: multipart/form-data; boundary=----WebKitFormBoundary7MA4YWxkTrZu0gW

------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="file"; filename="test-image.jpg"
Content-Type: image/jpeg

< ./img/input.png
------WebKitFormBoundary7MA4YWxkTrZu0gW--